### ISSUE TITLE
Create small Stories (issues) and tag them...

### ISSUE THREAD

**Issue by cicorias** [cs600f2016/FALL2016#1]
@cs600f2016

**Comment by vjrene** [comment]
@cicorias @cs600f2016 
1. As a college history student I want to explore my artistic side so that I can be more creative.
2. As a leadership executive I want employees who creatively work well together so that our business can communicate more effectively and encourage out of the box thinking.
3. As a mother of three, I want a low cost outside activity so that my children can explore their neighborhood and have a creative outlet.
4. As an art student I want to compete and network with other artists so that I can reciprocate creative knowledge with my peers.
5. As a high school art teacher I want to challenge my students with a weekend long assignment so that I can create a curated gallery of my students’ work.
6. As a social media enthusiast, I want more content to post and share so that I can get more followers/likes.
7. As a bored resident of Williamsburg, I want something fun to do that would involve the neighborhood/community.
8. As an accountant, I was able to explore my creative side and connect my coworkers on a more artistic level.
9. As a child I was inspired to create a Mother’s Day gift.

**Comment by cicorias** [comment]
I added markdown to number these.  These should be individual User Stories when you're ready.  On Zube.io there are "Cards"

One goal of a User Story is to make it "testable". What would be the acceptance criteria or for each story, when would the Product Owner say "it's done"?
1. sounds too high level to be aa story, it's really the purpose of the whole app - is that what you intended?  if so, then that can be part of the ReadMe.md in the root of this project.
2. is high level
3. is close, but it needs more - eg. As a ..  I need to find outside activities (? near me ? ) so I can ...
   then for 3. you can create an "Experience" in a series of Wireframes - that really becomes a StoryBoard.
4. Sounds like an "Epic" - which could be made up of many User Stories. This seems to be a high level feature that needs greater decomposition.

Writing User Stories is not a science. In fact, as you create, read them, you start seeing themes, patterns, etc.

From what's above - I'd focus on 4. or 3. as a starting point. Or 7. as well.  At this point we'll only do 1 of these high level "Epics"

Next step is "Pick" an epic, brief User Story that is "interactive" and Goal Oriented, not too broad. Then a basic Wireframe (electronic pen & paper, real pen & paper scanned - etc. low tech)..

Here's a PDF that could be used (printed out) to mock things up with a sharpie..  [Wireframe](https://d13yacurqjgara.cloudfront.net/users/107634/screenshots/1727466/attachments/278002/iPhone_6-template.pdf)
